version: '3'

services:
  # Define a Telegraf service
  # Define a Telegraf service
  telegraf-email:
    build: ~/monitoring/email
    volumes:
      - ~/monitoring/email/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  telegraf:
    image: telegraf:1.11
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_UDP_ENABLED: "true"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
    ports:
      - "8086:8086"
      - "8089:8089/udp"
  # Define a Chronograf service
  chronograf:
    image: chronograf:1.7.12
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.5.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      KAPACITOR_LOGGING_LEVEL: error
    links:
      - influxdb
    ports:
      - "9092:9092"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.3.5
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor:1.5.3
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor
